- name: Ensure swap is disabled
  command: dphys-swapfile swapoff
  become: true
  changed_when: false
  ignore_errors: true

- name: Set swap size in configuration
  lineinfile:
    path: /etc/dphys-swapfile
    regexp: "^CONF_SWAPSIZE"
    line: "CONF_SWAPSIZE={{ swap_size_mb }}"
    create: yes
  become: true

- name: Apply new swap configuration
  command: dphys-swapfile setup
  become: true

- name: Enable swap
  command: dphys-swapfile swapon
  become: true
